
namespace SharedComponents.EVE
{
    //
    //http://eve-markets.net/browse
    //
    public enum Group
    {
        Star = 6,
        Planet = 7,
        Moon = 8,
        AsteroidBelt = 9,
        Stargate = 10,
        Wormhole = 988,
        Station = 15,
        Citadel = 1657,
        AccelerationGate = 366,
        JumpBridge = 707,

        ForceField = 411,
        POSControlTower = 365,

        Capsule = 29,

        ProbeLauncher = 481,
        Probes = 479,

        // Note: This includes MicroWarpDrives as well!
        Afterburner = 46,

        Booster = 303,
        CapacitorInjector = 76,
        AncillaryShieldBooster = 1156,
        AncillaryArmorBooster = 1199,
        ShieldBoosters = 40,
        ShieldHardeners = 77,
        ShieldExtender = 38,
        ArmorRepairer = 62,
        ArmorHardeners = 328,
        AssaultDamageControl = 60,
        ArmorPlate = 329,
        DamageControl = 60,
        CapRecharger = 43,
        CapacitorFluxCoil = 768,
        CapacitorBattery = 61,
        CPUEnhancer = 285,
        DroneControlRange = 647,
        DroneDamageAmplifier = 645,
        ECCM = 202,
        CloakingDevice = 330,
        WarpCoreStabilizer = 315,
        InertialStabilizer = 762,
        Nanofiber = 763,
        PowerDiagnosticUnit = 766,
        ReactorControlUnit = 769,
        ShieldBoostAmplifier = 338,
        Shieldrecharger = 39,

        Gyrostabilizer = 59,
        HeatSink = 205,
        MagneticFieldStabilizer = 302,
        VortronProjectorUpgrade = 4067,

        TrackingLink = 209,
        DroneTrackingLink = 646,

        //TrackingEnhancer = 211, //no script needed
        SensorBooster = 212,

        SensorDampener = 208,
        TrackingComputer = 213,
        TrackingDisruptor = 291,
        MissileGuidanceComputer = 1396,
        Ecm = 201,

        TrackingScript = 907,
        WarpDisruptionScript = 908,
        TrackingDisruptionScript = 909,
        SensorBoosterScript = 910,
        SensorDampenerScript = 911,

        ProximityDrone = 97,
        CombatDrone = 100,
        MiningDrone = 101,
        FighterDrone = 549,
        ElectronicWarfareDrone = 639,
        LogisticsDrone = 640,
        WebbingDrone = 641,

        CapacitorGroupCharge = 87,
        CriminalTags = 370,
        EmpireInsigniaDrops = 409,

        AncillaryRemoteShieldBooster = 1697,
        AncillaryRemoteArmorRepairer = 1199,
        RemoteEnergyTransfer = 67,
        RemoteShieldRepairer = 41,
        RemoteArmorRepairer = 325,
        RemoteHullRepairer = 585,
        WarpDisruptor = 52,
        StasisWeb = 65,
        StasisGrappler = 1672,
        NOS = 68,
        Neutralizer = 71,
        TargetPainter = 379,
        BastionAndSiegeModules = 515,

        EnergyWeapon = 53,
        ProjectileWeapon = 55,
        HybridWeapon = 74,

        CruiseMissileLaunchers = 506,
        RocketLaunchers = 507,
        TorpedoLaunchers = 508,
        StandardMissileLaunchers = 56,
        HeavyMissileLaunchers = 510,
        AssaultMissileLaunchers = 511,
        HeavyAssaultMissileLaunchers = 771,
        LightMissileLaunchers = 509,
        DefenderMissileLaunchers = 512,
        CitadelCruiseLaunchers = 1674,
        CitadelTorpLaunchers = 524,
        RapidLightMissileLaunchers = 1245,
        RapidHeavyMissileLaunchers = 512,
        PrecursorWeapon = 1986,
        VortonProjector = 4060,

        SmartBomb = 72,

        Rockets = 387,
        LightMissiles = 384,
        HeavyMissiles = 385,
        HeavyAssaultMissiles = 772,
        CruiseMissiles = 386,
        Torpedoes = 89,

        ProjectileAmmo = 83,
        HybridCharge = 85,
        FrequencyCrystal = 86,

        AdvancedAutoCannonAmmo = 372,
        AdvancedRailgunCharge = 373,
        AdvancedBeamLaserCrystal = 374,
        AdvancedPulseLaserCrystal = 375,
        AdvancedArtilleryAmmo = 376,
        AdvancedBlasterCharge = 377,

        Miners = 54, // Miner I, Miner II, etc - Mining Tool GroupIDs
        GasCloudHarvester = 737,
        MiningLaser = 54,
        StripMiners = 464, // Strip Miner I, etc - Mining Tool GroupIDs
        ModulatedStripMiners = 483, // Modulated Strip Miners, etc - Mining Tool GroupIDs
        MiningBarge = 463,
        Exhumer = 543,
        IndustrialCommandShip = 941,
        CapitalIndustrialShip = 883,

        SentryGun = 99, //Protecting the weak and upholding the law

        ConcordBillboard = 323,
        ProtectiveSentryGun = 180,
        MobileSentryGun = 336,
        DestructibleSentryGun = 383,
        MobileMissileSentry = 417,
        MobileProjectileSentry = 426,
        MobileLaserSentry = 430,
        StasisWebificationBattery = 441,
        MobileHybridSentry = 449,
        DeadspaceOverseersSentry = 495,
        EnergyNeutralizingBattery = 837,

        LargeColidableStructure = 319,
        LargeColidableObject = 226,
        LargeColidableShip = 784,
        DeadSpaceOverseersSentry = 495,
        DeadSpaceOverseersStructure = 494,
        DeadSpaceOverseersBelongings = 496,

        AbyssalBioAdaptiveCache = 2009, //319,
        AbyssalDeadspaceTriglavianTransferConduit = 366, //same as a acceleration gate

        //AbyssalDeadspaceUnstableAbyssalDepths = 1971, //Uninteractable Localized Effect Beacon (Clouds)
        AbyssalFlagCruiser = 1972, //Flag Cruiser

        AbyssalDeadspaceAOE_structure = 1973, //Locators
        AbyssalStructureFestivalLauncher = 1974, //Structure Festival Launcher
        AbyssalDeadspaceWeather = 1975, //Non-Interactable Object
        AbyssalTrinaryDataVaults = 1977, //Trinary Data Vaults
        AbyssalIndustrialSupportFacility = 1978, //Industrial Support Facility
        AbyssalDeadspaceFilament = 1979, //Abyssal Filaments
        VoidSpaceFilament = 4743, //VoidSpace Filament
        AbyssalDeadspaceNonScalableCloud = 1980, //Non-Scalable Clouds
        AbyssalDeadspaceAoeTowerWeapon = 1981, //Triglavian Support Pylons
        AbyssalSpaceshipEntities = 1982, //Abyssal Spaceship Entities
        AbyssalDeadspace_Tier1_StrikingDamavik_RR = 1982,
        AbyssalEnviornment = 1983,
        AbyssalTrace = 1991, //Abyssal Trace: the entity in normal space that indicates someone jumped to Abyssal space from there (it is NOT a gate)
        AbyssalDeadspaceDroneEntities = 1997,
        InvadingPrecursorEntities = 4028,
        SoCTExpeditionWreckGroup = 367774,

        Mutaplasmids = 1964,

        CargoContainer = 12,
        SpawnContainer = 306,
        SecureContainer = 340,
        AuditLogSecureContainer = 448,
        FreightContainer = 649,
        MissionContainer = 952,

        Wreck = 186,

        PlayerDrone = 100,

        Livestock = 283, //this includes most CommonMissionCompletionitems like Militants and Marines
        MiscSpecialMissionItems = 314, //Misc special mission items that should not be on the market and not available from random missions.

        CustomsOffice = 1025,
        ConcordDrone = 301,
        PoliceDrone = 182,
        CustomsOfficial = 446,
        Billboard = 323,
        Merchant = 297,
        Mission_Merchant = 1006, //dread pirate scarlet
        FactionWarfareNPC = 288,
        GasCloud = 227,

        Shuttle = 31,
        Industrial = 28,
        TransportShip = 380,
        BlockadeRunner = 1202,
        Freighter = 513,
        JumpFreighter = 902,

        Frigate = 25,
        AssaultShip = 324,
        Destroyer = 420,
        TacticalDestroyer = 1305,
        CommandDestroyer = 1534,
        Interdictor = 541,
        CovertOpsFrigate = 830,
        Interceptor = 831,
        StealthBomber = 834,
        ElectronicAttackShip = 893,
        PrototypeExplorationShip = 1022,
        ExpeditionFrigate = 1283,

        RookieShip = 237,
        Cruiser = 26,
        HeavyAssaultShip = 358,
        AdvancedCruisers = 448,
        Logistics = 832,
        ForceReconShip = 833,
        CombatReconShip = 906,
        HeavyInterdictor = 894,

        Battlecruiser = 419,
        CommandShip = 540,
        StrategicCruiser = 963,

        Battleship = 27,
        EliteBattleship = 381,
        BlackOps = 898,
        Marauder = 900,

        Carrier = 574,
        Dreadnaught = 485,
        Titan = 30,

        SiegeModule = 515,
        Salvager = 1122,
        DataMiners = 538, //codebreaker, analyzer, data subverter
        TractorBeam = 650,

        Drugs = 313,
        ToxicWaste = 282,
        Slaves = 283,
        SmallArms = 280,
        AccelerationGateKeys = 474,
        Commodities = 526,

        Minerals = 18,

        ScienceSkillBooks = 270,

        MobileTractor = 1250,
        MobileDepot = 1246,
        MobileWarpDisruptor = 361,


        //
        // see https://wiki.eveuniversity.org/Asteroids_and_ore
        //
        Plagioclase = 458,
        Spodumain = 461,
        Kernite = 457,
        Hedbergite = 454,
        Arkonor = 450,
        Bistot = 451,
        Pyroxeres = 459,
        Crokite = 452,
        Jaspet = 456,
        Omber = 469,
        Scordite = 460,
        Gneiss = 467,
        Veldspar = 462,
        Hemorphite = 455,
        DarkOchre = 453,
        Ice = 465,

        //
        // various NPCs
        //
        DeepFlowFrigateDrone = 1568,
        DeepFlowDestroyerDrone = 1664,
        DeepFlowAdaptiveCanisterGroup = 1194,

        Deadspace_Rogue_Drone_Swarm = 806,

        TutorialDrone = 286,
        Storyline_Battleship = 523,
        Storyline_Mission_Battleship = 534,
        Asteroid_Angel_Cartel_Battleship = 552,
        Asteroid_Blood_Raiders_Battleship = 556,
        Asteroid_Guristas_Battleship = 560,
        Asteroid_Sanshas_Nation_Battleship = 565,
        Asteroid_Serpentis_Battleship = 570,
        Deadspace_Angel_Cartel_Battleship = 594,
        Deadspace_Blood_Raiders_Battleship = 603,
        Deadspace_Guristas_Battleship = 612,
        Deadspace_Sanshas_Nation_Battleship = 621,
        Deadspace_Serpentis_Battleship = 630,
        Mission_Amarr_Empire_Battleship = 667,
        Mission_Caldari_State_Battleship = 674,
        Mission_Gallente_Federation_Battleship = 680,
        Mission_Khanid_Battleship = 691,
        Mission_CONCORD_Battleship = 697,
        Mission_Mordu_Battleship = 703,
        Mission_Minmatar_Republic_Battleship = 706,
        Asteroid_Rogue_Drone_Battleship = 756,
        Deadspace_Rogue_Drone_Battleship = 802,
        Mission_Generic_Battleships = 816,
        Deadspace_Overseer_Battleship = 821,
        Mission_Thukker_Battleship = 823,
        Asteroid_Rogue_Drone_Commander_Battleship = 844,
        Asteroid_Angel_Cartel_Commander_Battleship = 848,
        Asteroid_Blood_Raiders_Commander_Battleship = 849,
        Asteroid_Guristas_Commander_Battleship = 850,
        Asteroid_Sanshas_Nation_Commander_Battleship = 851,
        Asteroid_Serpentis_Commander_Battleship = 852,
        Mission_Faction_Battleship = 924,
        Asteroid_Angel_Cartel_BattleCruiser = 576,
        Asteroid_Blood_Raiders_BattleCruiser = 578,
        Asteroid_Guristas_BattleCruiser = 580,
        Asteroid_Sanshas_Nation_BattleCruiser = 582,
        Asteroid_Serpentis_BattleCruiser = 584,
        Deadspace_Angel_Cartel_BattleCruiser = 593,
        Deadspace_Blood_Raiders_BattleCruiser = 602,
        Deadspace_Guristas_BattleCruiser = 611,
        Deadspace_Sanshas_Nation_BattleCruiser = 620,
        Deadspace_Serpentis_BattleCruiser = 629,
        Mission_Amarr_Empire_Battlecruiser = 666,
        Mission_Caldari_State_Battlecruiser = 672,
        Mission_Gallente_Federation_Battlecruiser = 681,
        Mission_Minmatar_Republic_Battlecruiser = 685,
        Mission_Khanid_Battlecruiser = 690,
        Mission_CONCORD_Battlecruiser = 696,
        Mission_Faction_Industrials = 927,
        Mission_Mordu_Battlecruiser = 702,
        Asteroid_Rogue_Drone_BattleCruiser = 755,
        Asteroid_Angel_Cartel_Commander_BattleCruiser = 793,
        Asteroid_Blood_Raiders_Commander_BattleCruiser = 795,
        Asteroid_Guristas_Commander_BattleCruiser = 797,
        Deadspace_Rogue_Drone_BattleCruiser = 801,
        Asteroid_Sanshas_Nation_Commander_BattleCruiser = 807,
        Asteroid_Serpentis_Commander_BattleCruiser = 811,
        Mission_Thukker_Battlecruiser = 822,
        Asteroid_Rogue_Drone_Commander_BattleCruiser = 843,
        Storyline_Cruiser = 522,
        Storyline_Mission_Cruiser = 533,
        Asteroid_Angel_Cartel_Cruiser = 551,
        Asteroid_Blood_Raiders_Cruiser = 555,
        Asteroid_Guristas_Cruiser = 561,
        Asteroid_Sanshas_Nation_Cruiser = 566,
        Asteroid_Serpentis_Cruiser = 571,
        Deadspace_Angel_Cartel_Cruiser = 595,
        Deadspace_Blood_Raiders_Cruiser = 604,
        Deadspace_Guristas_Cruiser = 613,
        Deadspace_Sanshas_Nation_Cruiser = 622,
        Deadspace_Serpentis_Cruiser = 631,
        Mission_Amarr_Empire_Cruiser = 668,
        Mission_Caldari_State_Cruiser = 673,
        Mission_Gallente_Federation_Cruiser = 678,
        Mission_Khanid_Cruiser = 689,
        Mission_CONCORD_Cruiser = 695,
        Mission_Mordu_Cruiser = 701,
        Mission_Minmatar_Republic_Cruiser = 705,
        Asteroid_Rogue_Drone_Cruiser = 757,
        Asteroid_Angel_Cartel_Commander_Cruiser = 790,
        Asteroid_Blood_Raiders_Commander_Cruiser = 791,
        Asteroid_Guristas_Commander_Cruiser = 798,
        Deadspace_Rogue_Drone_Cruiser = 803,
        Asteroid_Sanshas_Nation_Commander_Cruiser = 808,
        Asteroid_Serpentis_Commander_Cruiser = 812,
        Mission_Generic_Cruisers = 817,
        Deadspace_Overseer_Cruiser = 820,
        Mission_Thukker_Cruiser = 824,
        Mission_Generic_Battle_Cruisers = 828,
        Asteroid_Rogue_Drone_Commander_Cruiser = 845,
        Mission_Faction_Cruiser = 1006,
        Asteroid_Angel_Cartel_Destroyer = 575,
        Asteroid_Blood_Raiders_Destroyer = 577,
        Asteroid_Guristas_Destroyer = 579,
        Asteroid_Sanshas_Nation_Destroyer = 581,
        Asteroid_Serpentis_Destroyer = 583,
        Deadspace_Angel_Cartel_Destroyer = 596,
        Deadspace_Blood_Raiders_Destroyer = 605,
        Deadspace_Guristas_Destroyer = 614,
        Deadspace_Sanshas_Nation_Destroyer = 623,
        Deadspace_Serpentis_Destroyer = 632,
        Mission_Amarr_Empire_Destroyer = 669,
        Mission_Caldari_State_Destroyer = 676,
        Mission_Gallente_Federation_Destroyer = 679,
        Mission_Minmatar_Republic_Destroyer = 684,
        Mission_Khanid_Destroyer = 688,
        Mission_CONCORD_Destroyer = 694,
        Mission_Mordu_Destroyer = 700,
        Asteroid_Rogue_Drone_Destroyer = 758,
        Asteroid_Angel_Cartel_Commander_Destroyer = 794,
        Asteroid_Blood_Raiders_Commander_Destroyer = 796,
        Asteroid_Guristas_Commander_Destroyer = 799,
        Deadspace_Rogue_Drone_Destroyer = 804,
        Asteroid_Sanshas_Nation_Commander_Destroyer = 809,
        Asteroid_Serpentis_Commander_Destroyer = 813,
        Mission_Thukker_Destroyer = 825,
        Mission_Generic_Destroyers = 829,
        Asteroid_Rogue_Drone_Commander_Destroyer = 846,
        asteroid_angel_cartel_frigate = 550,
        asteroid_blood_raiders_frigate = 557,
        asteroid_guristas_frigate = 562,
        asteroid_sanshas_nation_frigate = 567,
        asteroid_serpentis_frigate = 572,
        deadspace_angel_cartel_frigate = 597,
        deadspace_blood_raiders_frigate = 606,
        deadspace_guristas_frigate = 615,
        deadspace_sanshas_nation_frigate = 624,
        deadspace_serpentis_frigate = 633,
        mission_amarr_empire_frigate = 665,
        mission_caldari_state_frigate = 671,
        mission_gallente_federation_frigate = 677,
        mission_minmatar_republic_frigate = 683,
        mission_khanid_frigate = 687,
        mission_concord_frigate = 693,
        mission_mordu_frigate = 699,
        asteroid_rouge_drone_frigate = 759,
        deadspace_rogue_drone_frigate = 805,
        asteroid_angel_cartel_commander_frigate = 789,
        asteroid_blood_raiders_commander_frigate = 792,
        asteroid_guristas_commander_frigate = 800,
        asteroid_sanshas_nation_commander_frigate = 810,
        asteroid_serpentis_commander_frigate = 814,
        mission_generic_frigates = 818,
        Deadspace_Overseer_Frigate = 819,
        mission_thukker_frigate = 826,
        asteroid_rouge_drone_commander_frigate = 847,
        Deadspace_Sleeper_Sleepless_Sentinel = 959,
        Deadspace_Sleeper_Awakened_Sentinel = 960,
        Deadspace_Sleeper_Emergent_Sentinel = 961,
        Deadspace_Sleeper_Sleepless_Defender = 982,
        Deadspace_Sleeper_Sleepless_Patroller = 983,
        Deadspace_Sleeper_Awakened_Defender = 984,
        Deadspace_Sleeper_Awakened_Patroller = 985,
        Deadspace_Sleeper_Emergent_Defender = 986,
        Deadspace_Sleeper_Emergent_Patroller = 987,
        Drifters_Battleship = 1310,
        DrifterResponseBattleship = 1530,
        DrifterReinforcements = 1956,
        Asteroid_Guristas_Officer = 504,
        Asteroid_Angel_Cartel_Officer = 553,
        Asteroid_Blood_Raiders_Officer = 559,
        Asteroid_Rogue_Drone_Officer = 1174,
        Asteroid_Sanshas_Nation_Officer = 569,
        Asteroid_Serpentis_Officer = 574,

        Pirate_Capsule = 4501,
        GuristasHuntCapsule = 4053,
    }
}