Set-ProcessMitigation System -disable AllowStoreSignedBinaries
Set-ProcessMitigation System -disable AllowThreadsToOptOut
Set-ProcessMitigation System -disable BlockDynamicCode
Set-ProcessMitigation System -disable BlockLowLabelImageLoads
Set-ProcessMitigation system -disable BlockRemoteImageLoads
Set-ProcessMitigation system -disable BottomUp
Set-ProcessMitigation system -disable CFG
Set-ProcessMitigation system -disable DEP
Set-ProcessMitigation System -disable DisableExtensionPoints
Set-ProcessMitigation System -disable DisableNonSystemFonts
Set-ProcessMitigation System -disable DisableWin32kSystemCalls
Set-ProcessMitigation System -disable DisallowChildProcessCreation
Set-ProcessMitigation System -disable EmulateAtlThunks
Set-ProcessMitigation system -disable EnableExportAddressFilter
Set-ProcessMitigation system -disable EnableExportAddressFilterPlus
Set-ProcessMitigation system -disable EnableImportAddressFilter
Set-ProcessMitigation system -disable EnableRopCallerCheck
Set-ProcessMitigation system -disable EnableRopSimExec
Set-ProcessMitigation system -disable EnableRopStackPivot
Set-ProcessMitigation System -disable EnforceModuleDependencySigning
Set-ProcessMitigation system -disable ForceRelocateImages
Set-ProcessMitigation System -disable HighEntropy
Set-ProcessMitigation System -disable MicrosoftSignedOnly
Set-ProcessMitigation System -disable PreferSystem32
Set-ProcessMitigation System -disable RequireInfo
Set-ProcessMitigation system -disable SEHOP
Set-ProcessMitigation system -disable StrictHandle
Set-ProcessMitigation system -disable SuppressExports
Set-ProcessMitigation system -disable TerminateOnError

