using System;

namespace SharedComponents.EVE.Types
{
    [Serializable]
    public enum InvasionType
    {
        INVASION_CHAPTER_THREE_SCOUTS_AND_PATROLS = 99, // stellar recog
        INVASION_CHAPTER_THREE_TRIGLAVIAN_ESTABLISHMENT = 100, // escalating lim.
        INVASION_CHAPTER_THREE_EMPIRE_FORTIFICATION = 101, // redoubts & bulw.
        INVASION_CHAPTER_THREE_TRIGLAVIAN_VICTORY = 102, //  final lim.
        INVASION_CHAPTER_THREE_EMPIRE_VICTORY = 103, // edencom fort.
        IMVASION_CHAPTER_THREE_TRIGLAVIAN_MINOR_VICTORY = 105,
        IMVASION_CHAPTER_THREE_EDENCOM_MINOR_VICTORY = 106,
        IMVASION_CHAPTER_THREE_MASSIVE_EDENCOM_FORTIFICATION = 110,
        IMVASION_CHAPTER_THREE_MASSIVE_TRIGLAVIAN_INVASION = 111,
    }
}